# Generated by Django 4.0.6 on 2022-07-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=30)),
                ('ram', models.TextField(blank=True, max_length=30)),
                ('rom', models.TextField(blank=True, max_length=30)),
                ('price', models.TextField(blank=True, max_length=30)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='dokan/images')),
            ],
        ),
    ]
